FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

RUN python -m pip install --upgrade pip setuptools wheel

RUN python -m pip install \
    azureml-inference-server-http==1.3.0 \
    pillow==10.4.0 \
    numpy==1.26.4
