no-autoupdate: true
protocol: quic
ingress:
  - hostname: int-api.onmu.cloud
    service: http://localhost:18080
  - hostname: db-int.onmu.cloud
    service: tcp://localhost:16432
  - service: http_status:404
